#Configuracoes do FarmaEtiquetas
#Thu Apr 30 10:53:43 BRT 2026
apiKey=4dd48459-d4e1-4dfd-a158-e2485a8727a4
apiUrl=http\://localhost\:8081
caminhoSaida=C\:/Etiquetas
dbBanco=sgfpod1
dbHost=192.168.15.201
dbPorta=5432
dbSenha=consultoria123
dbUsuario=consulta
nomeImpressora=
